dist: trusty
sudo: required
group: beta
language: node_js
node_js:
  - "6"
install:
  - npm install -g truffle
  - npm install -g ethereumjs-testrpc
  - npm install
cache:
  yarn: true
env:
  -
matrix:
  fast_finish: true
script:
  - yarn test
